package language

// Updated at: 2021-04-13 18:49:57.900128852 +0300 MSK m=+1.164995700
var List = []Language{
	{Alpha2: "FJ", Alpha3: "FIJ", Name: "Fijian", AltNames: []string(nil), Tags: []string{"fijian"}, Users: []string{"FJI"}},
	{Alpha2: "GU", Alpha3: "GUJ", Name: "Gujarati", AltNames: []string(nil), Tags: []string{"gujarati"}, Users: []string(nil)},
	{Alpha2: "TL", Alpha3: "TGL", Name: "Tagalog", AltNames: []string(nil), Tags: []string{"tagalog"}, Users: []string(nil)},
	{Alpha2: "ZU", Alpha3: "ZUL", Name: "Zulu", AltNames: []string(nil), Tags: []string{"zulu"}, Users: []string{"ZAF"}},
	{Alpha2: "AF", Alpha3: "AFR", Name: "Afrikaans", AltNames: []string(nil), Tags: []string{"afrikaans"}, Users: []string{"ZAF", "NAM"}},
	{Alpha2: "BS", Alpha3: "BOS", Name: "Bosnian", AltNames: []string(nil), Tags: []string{"bosnian"}, Users: []string{"MNE", "BIH"}},
	{Alpha2: "NO", Alpha3: "NOR", Name: "Norwegian", AltNames: []string(nil), Tags: []string{"norwegian"}, Users: []string{"BVT", "NOR", "SJM"}},
	{Alpha2: "DZ", Alpha3: "DZO", Name: "Dzongkha", AltNames: []string(nil), Tags: []string{"dzongkha"}, Users: []string{"BTN"}},
	{Alpha2: "EN", Alpha3: "ENG", Name: "English", AltNames: []string(nil), Tags: []string{"english"}, Users: []string{"PHL", "SYC", "GRD", "TZA", "ZMB", "SDN", "VIR", "HKG", "TON", "SXM", "ZWE", "COK", "SGS", "TTO", "ATA", "MHL", "GBR", "VCT", "SWZ", "TUV", "BWA", "CCK", "ERI", "VGB", "KNA", "AIA", "MUS", "VUT", "BLZ", "SHN", "ATG", "NRU", "IMN", "FSM", "CXR", "HMD", "NIU", "SLE", "JEY", "JAM", "RWA", "FLK", "KIR", "ZAF", "IND", "AUS", "PCN", "BHS", "GGY", "MAF", "NZL", "PAK", "GMB", "PNG", "WSM", "CUW", "GHA", "IRL", "BRB", "BMU", "MSR", "SGP", "MWI", "MNP", "USA", "KEN", "LSO", "CMR", "CYM", "GUM", "NAM", "NGA", "NFK", "TKL", "PRI", "SSD", "LBR", "MLT", "PLW", "ASM", "TCA", "SLB", "FJI", "UGA", "CAN", "DMA", "IOT", "LCA", "GIB", "GUY"}},
	{Alpha2: "GA", Alpha3: "GLE", Name: "Irish", AltNames: []string(nil), Tags: []string{"irish"}, Users: []string{"IRL"}},
	{Alpha2: "HZ", Alpha3: "HER", Name: "Herero", AltNames: []string(nil), Tags: []string{"herero"}, Users: []string(nil)},
	{Alpha2: "TK", Alpha3: "TUK", Name: "Turkmen", AltNames: []string(nil), Tags: []string{"turkmen"}, Users: []string{"AFG", "TKM"}},
	{Alpha2: "AE", Alpha3: "AVE", Name: "Avestan", AltNames: []string(nil), Tags: []string{"avestan"}, Users: []string(nil)},
	{Alpha2: "EO", Alpha3: "EPO", Name: "Esperanto", AltNames: []string(nil), Tags: []string{"esperanto"}, Users: []string(nil)},
	{Alpha2: "SL", Alpha3: "SLV", Name: "Slovenian", AltNames: []string(nil), Tags: []string{"slovenian"}, Users: []string{"SVN"}},
	{Alpha2: "SD", Alpha3: "SND", Name: "Sindhi", AltNames: []string(nil), Tags: []string{"sindhi"}, Users: []string(nil)},
	{Alpha2: "BA", Alpha3: "BAK", Name: "Bashkir", AltNames: []string(nil), Tags: []string{"bashkir"}, Users: []string(nil)},
	{Alpha2: "ET", Alpha3: "EST", Name: "Estonian", AltNames: []string(nil), Tags: []string{"estonian"}, Users: []string{"EST"}},
	{Alpha2: "HE", Alpha3: "HEB", Name: "Hebrew", AltNames: []string(nil), Tags: []string{"hebrew"}, Users: []string{"ISR"}},
	{Alpha2: "LG", Alpha3: "LUG", Name: "Ganda", AltNames: []string(nil), Tags: []string{"ganda"}, Users: []string(nil)},
	{Alpha2: "RU", Alpha3: "RUS", Name: "Russian", AltNames: []string(nil), Tags: []string{"russian"}, Users: []string{"ATA", "UZB", "KGZ", "BLR", "TKM", "RUS", "ARM", "TJK", "KAZ"}},
	{Alpha2: "AK", Alpha3: "AKA", Name: "Akan", AltNames: []string(nil), Tags: []string{"akan"}, Users: []string(nil)},
	{Alpha2: "BR", Alpha3: "BRE", Name: "Breton", AltNames: []string(nil), Tags: []string{"breton"}, Users: []string(nil)},
	{Alpha2: "TS", Alpha3: "TSO", Name: "Tsonga", AltNames: []string(nil), Tags: []string{"tsonga"}, Users: []string{"ZAF"}},
	{Alpha2: "BE", Alpha3: "BEL", Name: "Belarusian", AltNames: []string(nil), Tags: []string{"belarusian"}, Users: []string{"BLR"}},
	{Alpha2: "LO", Alpha3: "LAO", Name: "Lao", AltNames: []string(nil), Tags: []string{"lao"}, Users: []string{"LAO"}},
	{Alpha2: "ML", Alpha3: "MAL", Name: "Malayalam", AltNames: []string(nil), Tags: []string{"malayalam"}, Users: []string(nil)},
	{Alpha2: "SG", Alpha3: "SAG", Name: "Sango", AltNames: []string(nil), Tags: []string{"sango"}, Users: []string{"CAF"}},
	{Alpha2: "VE", Alpha3: "VEN", Name: "Venda", AltNames: []string(nil), Tags: []string{"venda"}, Users: []string{"ZAF"}},
	{Alpha2: "KS", Alpha3: "KAS", Name: "Kashmiri", AltNames: []string(nil), Tags: []string{"kashmiri"}, Users: []string(nil)},
	{Alpha2: "KV", Alpha3: "KOM", Name: "Komi", AltNames: []string(nil), Tags: []string{"komi"}, Users: []string(nil)},
	{Alpha2: "TT", Alpha3: "TAT", Name: "Tatar", AltNames: []string(nil), Tags: []string{"tatar"}, Users: []string(nil)},
	{Alpha2: "AA", Alpha3: "AAR", Name: "Afar", AltNames: []string(nil), Tags: []string{"afar"}, Users: []string(nil)},
	{Alpha2: "HI", Alpha3: "HIN", Name: "Hindi", AltNames: []string(nil), Tags: []string{"hindi"}, Users: []string{"IND", "FJI"}},
	{Alpha2: "SV", Alpha3: "SWE", Name: "Swedish", AltNames: []string(nil), Tags: []string{"swedish"}, Users: []string{"ALA", "SWE", "FIN"}},
	{Alpha2: "TH", Alpha3: "THA", Name: "Thai", AltNames: []string(nil), Tags: []string{"thai"}, Users: []string{"THA"}},
	{Alpha2: "UZ", Alpha3: "UZB", Name: "Uzbek", AltNames: []string(nil), Tags: []string{"uzbek"}, Users: []string{"UZB", "AFG"}},
	{Alpha2: "BG", Alpha3: "BUL", Name: "Bulgarian", AltNames: []string(nil), Tags: []string{"bulgarian"}, Users: []string{"BGR"}},
	{Alpha2: "CO", Alpha3: "COS", Name: "Corsican", AltNames: []string(nil), Tags: []string{"corsican"}, Users: []string(nil)},
	{Alpha2: "HU", Alpha3: "HUN", Name: "Hungarian", AltNames: []string(nil), Tags: []string{"hungarian"}, Users: []string{"HUN"}},
	{Alpha2: "OJ", Alpha3: "OJI", Name: "Ojibwa", AltNames: []string(nil), Tags: []string{"ojibwa"}, Users: []string(nil)},
	{Alpha2: "AM", Alpha3: "AMH", Name: "Amharic", AltNames: []string(nil), Tags: []string{"amharic"}, Users: []string{"ETH"}},
	{Alpha2: "IG", Alpha3: "IBO", Name: "Igbo", AltNames: []string(nil), Tags: []string{"igbo"}, Users: []string(nil)},
	{Alpha2: "LV", Alpha3: "LAV", Name: "Latvian", AltNames: []string(nil), Tags: []string{"latvian"}, Users: []string{"LVA"}},
	{Alpha2: "SU", Alpha3: "SUN", Name: "Sundanese", AltNames: []string(nil), Tags: []string{"sundanese"}, Users: []string(nil)},
	{Alpha2: "WO", Alpha3: "WOL", Name: "Wolof", AltNames: []string(nil), Tags: []string{"wolof"}, Users: []string(nil)},
	{Alpha2: "EE", Alpha3: "EWE", Name: "Ewe", AltNames: []string(nil), Tags: []string{"ewe"}, Users: []string(nil)},
	{Alpha2: "GL", Alpha3: "GLG", Name: "Galician", AltNames: []string(nil), Tags: []string{"galician"}, Users: []string(nil)},
	{Alpha2: "KN", Alpha3: "KAN", Name: "Kannada", AltNames: []string(nil), Tags: []string{"kannada"}, Users: []string(nil)},
	{Alpha2: "NA", Alpha3: "NAU", Name: "Nauru", AltNames: []string(nil), Tags: []string{"nauru"}, Users: []string{"NRU"}},
	{Alpha2: "PT", Alpha3: "POR", Name: "Portuguese", AltNames: []string(nil), Tags: []string{"portuguese"}, Users: []string{"MOZ", "MAC", "AGO", "BRA", "STP", "CPV", "GNB", "PRT", "TLS"}},
	{Alpha2: "SM", Alpha3: "SMO", Name: "Samoan", AltNames: []string(nil), Tags: []string{"samoan"}, Users: []string{"WSM", "ASM"}},
	{Alpha2: "RM", Alpha3: "ROH", Name: "Romansh", AltNames: []string(nil), Tags: []string{"romansh"}, Users: []string(nil)},
	{Alpha2: "TN", Alpha3: "TSN", Name: "Tswana", AltNames: []string(nil), Tags: []string{"tswana"}, Users: []string{"BWA", "ZAF"}},
	{Alpha2: "WA", Alpha3: "WLN", Name: "Walloon", AltNames: []string(nil), Tags: []string{"walloon"}, Users: []string(nil)},
	{Alpha2: "YI", Alpha3: "YID", Name: "Yiddish", AltNames: []string(nil), Tags: []string{"yiddish"}, Users: []string(nil)},
	{Alpha2: "AY", Alpha3: "AYM", Name: "Aymara", AltNames: []string(nil), Tags: []string{"aymara"}, Users: []string{"BOL"}},
	{Alpha2: "GN", Alpha3: "GRN", Name: "Guarani", AltNames: []string(nil), Tags: []string{"guarani"}, Users: []string{"ARG", "PRY"}},
	{Alpha2: "IT", Alpha3: "ITA", Name: "Italian", AltNames: []string(nil), Tags: []string{"italian"}, Users: []string{"ITA", "CHE", "VAT", "SMR"}},
	{Alpha2: "JA", Alpha3: "JPN", Name: "Japanese", AltNames: []string(nil), Tags: []string{"japanese"}, Users: []string{"JPN"}},
	{Alpha2: "SN", Alpha3: "SNA", Name: "Shona", AltNames: []string(nil), Tags: []string{"shona"}, Users: []string{"ZWE"}},
	{Alpha2: "UK", Alpha3: "UKR", Name: "Ukrainian", AltNames: []string(nil), Tags: []string{"ukrainian"}, Users: []string{"UKR"}},
	{Alpha2: "DA", Alpha3: "DAN", Name: "Danish", AltNames: []string(nil), Tags: []string{"danish"}, Users: []string{"DNK"}},
	{Alpha2: "IO", Alpha3: "IDO", Name: "Ido", AltNames: []string(nil), Tags: []string{"ido"}, Users: []string(nil)},
	{Alpha2: "KK", Alpha3: "KAZ", Name: "Kazakh", AltNames: []string(nil), Tags: []string{"kazakh"}, Users: []string{"KAZ"}},
	{Alpha2: "TI", Alpha3: "TIR", Name: "Tigrinya", AltNames: []string(nil), Tags: []string{"tigrinya"}, Users: []string{"ERI"}},
	{Alpha2: "TW", Alpha3: "TWI", Name: "Twi", AltNames: []string(nil), Tags: []string{"twi"}, Users: []string(nil)},
	{Alpha2: "XH", Alpha3: "XHO", Name: "Xhosa", AltNames: []string(nil), Tags: []string{"xhosa"}, Users: []string{"ZAF"}},
	{Alpha2: "AB", Alpha3: "ABK", Name: "Abkhazian", AltNames: []string(nil), Tags: []string{"abkhazian"}, Users: []string(nil)},
	{Alpha2: "AS", Alpha3: "ASM", Name: "Assamese", AltNames: []string(nil), Tags: []string{"assamese"}, Users: []string(nil)},
	{Alpha2: "CR", Alpha3: "CRE", Name: "Cree", AltNames: []string(nil), Tags: []string{"cree"}, Users: []string(nil)},
	{Alpha2: "SA", Alpha3: "SAN", Name: "Sanskrit", AltNames: []string(nil), Tags: []string{"sanskrit"}, Users: []string(nil)},
	{Alpha2: "SC", Alpha3: "SRD", Name: "Sardinian", AltNames: []string(nil), Tags: []string{"sardinian"}, Users: []string(nil)},
	{Alpha2: "VI", Alpha3: "VIE", Name: "Vietnamese", AltNames: []string(nil), Tags: []string{"vietnamese"}, Users: []string{"VNM"}},
	{Alpha2: "HR", Alpha3: "HRV", Name: "Croatian", AltNames: []string(nil), Tags: []string{"croatian"}, Users: []string{"HRV", "MNE", "BIH"}},
	{Alpha2: "MN", Alpha3: "MON", Name: "Mongolian", AltNames: []string(nil), Tags: []string{"mongolian"}, Users: []string{"MNG"}},
	{Alpha2: "RN", Alpha3: "RUN", Name: "Rundi", AltNames: []string(nil), Tags: []string{"rundi"}, Users: []string{"BDI"}},
	{Alpha2: "YO", Alpha3: "YOR", Name: "Yoruba", AltNames: []string(nil), Tags: []string{"yoruba"}, Users: []string(nil)},
	{Alpha2: "AR", Alpha3: "ARA", Name: "Arabic", AltNames: []string(nil), Tags: []string{"arabic"}, Users: []string{"YEM", "KWT", "SDN", "OMN", "QAT", "ERI", "ARE", "SAU", "COM", "IRQ", "SYR", "TCD", "LBN", "ISR", "EGY", "LBY", "DZA", "PSE", "MRT", "MAR", "JOR", "TUN", "BHR", "DJI", "SOM"}},
	{Alpha2: "BN", Alpha3: "BEN", Name: "Bengali", AltNames: []string(nil), Tags: []string{"bengali"}, Users: []string{"BGD"}},
	{Alpha2: "SS", Alpha3: "SSW", Name: "Swati", AltNames: []string(nil), Tags: []string{"swati"}, Users: []string{"SWZ", "ZAF"}},
	{Alpha2: "BI", Alpha3: "BIS", Name: "Bislama", AltNames: []string(nil), Tags: []string{"bislama"}, Users: []string{"VUT"}},
	{Alpha2: "FI", Alpha3: "FIN", Name: "Finnish", AltNames: []string(nil), Tags: []string{"finnish"}, Users: []string{"FIN"}},
	{Alpha2: "LA", Alpha3: "LAT", Name: "Latin", AltNames: []string(nil), Tags: []string{"latin"}, Users: []string{"VAT"}},
	{Alpha2: "MT", Alpha3: "MLT", Name: "Maltese", AltNames: []string(nil), Tags: []string{"maltese"}, Users: []string{"MLT"}},
	{Alpha2: "SO", Alpha3: "SOM", Name: "Somali", AltNames: []string(nil), Tags: []string{"somali"}, Users: []string{"SOM"}},
	{Alpha2: "TY", Alpha3: "TAH", Name: "Tahitian", AltNames: []string(nil), Tags: []string{"tahitian"}, Users: []string(nil)},
	{Alpha2: "AV", Alpha3: "AVA", Name: "Avaric", AltNames: []string(nil), Tags: []string{"avaric"}, Users: []string(nil)},
	{Alpha2: "AZ", Alpha3: "AZE", Name: "Azerbaijani", AltNames: []string(nil), Tags: []string{"azerbaijani"}, Users: []string{"AZE"}},
	{Alpha2: "KW", Alpha3: "COR", Name: "Cornish", AltNames: []string(nil), Tags: []string{"cornish"}, Users: []string(nil)},
	{Alpha2: "JV", Alpha3: "JAV", Name: "Javanese", AltNames: []string(nil), Tags: []string{"javanese"}, Users: []string(nil)},
	{Alpha2: "MH", Alpha3: "MAH", Name: "Marshallese", AltNames: []string(nil), Tags: []string{"marshallese"}, Users: []string{"MHL"}},
	{Alpha2: "SR", Alpha3: "SRP", Name: "Serbian", AltNames: []string(nil), Tags: []string{"serbian"}, Users: []string{"KOS", "MNE", "BIH", "SRB"}},
	{Alpha2: "UR", Alpha3: "URD", Name: "Urdu", AltNames: []string(nil), Tags: []string{"urdu"}, Users: []string{"PAK", "FJI"}},
	{Alpha2: "BM", Alpha3: "BAM", Name: "Bambara", AltNames: []string(nil), Tags: []string{"bambara"}, Users: []string(nil)},
	{Alpha2: "IK", Alpha3: "IPK", Name: "Inupiaq", AltNames: []string(nil), Tags: []string{"inupiaq"}, Users: []string(nil)},
	{Alpha2: "KR", Alpha3: "KAU", Name: "Kanuri", AltNames: []string(nil), Tags: []string{"kanuri"}, Users: []string(nil)},
	{Alpha2: "AN", Alpha3: "ARG", Name: "Aragonese", AltNames: []string(nil), Tags: []string{"aragonese"}, Users: []string(nil)},
	{Alpha2: "IU", Alpha3: "IKU", Name: "Inuktitut", AltNames: []string(nil), Tags: []string{"inuktitut"}, Users: []string(nil)},
	{Alpha2: "ID", Alpha3: "IND", Name: "Indonesian", AltNames: []string(nil), Tags: []string{"indonesian"}, Users: []string{"IDN"}},
	{Alpha2: "TR", Alpha3: "TUR", Name: "Turkish", AltNames: []string(nil), Tags: []string{"turkish"}, Users: []string{"CYP", "TUR"}},
	{Alpha2: "RW", Alpha3: "KIN", Name: "Kinyarwanda", AltNames: []string(nil), Tags: []string{"kinyarwanda"}, Users: []string{"RWA"}},
	{Alpha2: "LN", Alpha3: "LIN", Name: "Lingala", AltNames: []string(nil), Tags: []string{"lingala"}, Users: []string{"COD", "COG"}},
	{Alpha2: "MR", Alpha3: "MAR", Name: "Marathi", AltNames: []string(nil), Tags: []string{"marathi"}, Users: []string(nil)},
	{Alpha2: "PI", Alpha3: "PLI", Name: "Pali", AltNames: []string(nil), Tags: []string{"pali"}, Users: []string(nil)},
	{Alpha2: "CH", Alpha3: "CHA", Name: "Chamorro", AltNames: []string(nil), Tags: []string{"chamorro"}, Users: []string{"MNP", "GUM"}},
	{Alpha2: "GV", Alpha3: "GLV", Name: "Manx", AltNames: []string(nil), Tags: []string{"manx"}, Users: []string{"IMN"}},
	{Alpha2: "KG", Alpha3: "KON", Name: "Kongo", AltNames: []string(nil), Tags: []string{"kongo"}, Users: []string{"COD"}},
	{Alpha2: "KO", Alpha3: "KOR", Name: "Korean", AltNames: []string(nil), Tags: []string{"korean"}, Users: []string{"KOR", "PRK"}},
	{Alpha2: "LT", Alpha3: "LIT", Name: "Lithuanian", AltNames: []string(nil), Tags: []string{"lithuanian"}, Users: []string{"LTU"}},
	{Alpha2: "TA", Alpha3: "TAM", Name: "Tamil", AltNames: []string(nil), Tags: []string{"tamil"}, Users: []string{"LKA", "SGP"}},
	{Alpha2: "CV", Alpha3: "CHV", Name: "Chuvash", AltNames: []string(nil), Tags: []string{"chuvash"}, Users: []string(nil)},
	{Alpha2: "FF", Alpha3: "FUL", Name: "Fulah", AltNames: []string(nil), Tags: []string{"fulah"}, Users: []string{"BFA", "GIN"}},
	{Alpha2: "QU", Alpha3: "QUE", Name: "Quechua", AltNames: []string(nil), Tags: []string{"quechua"}, Users: []string{"BOL"}},
	{Alpha2: "SW", Alpha3: "SWA", Name: "Swahili", AltNames: []string(nil), Tags: []string{"swahili"}, Users: []string{"TZA", "COD", "KEN", "UGA"}},
	{Alpha2: "FO", Alpha3: "FAO", Name: "Faroese", AltNames: []string(nil), Tags: []string{"faroese"}, Users: []string{"FRO"}},
	{Alpha2: "KU", Alpha3: "KUR", Name: "Kurdish", AltNames: []string(nil), Tags: []string{"kurdish"}, Users: []string{"IRQ"}},
	{Alpha2: "NG", Alpha3: "NDO", Name: "Ndonga", AltNames: []string(nil), Tags: []string{"ndonga"}, Users: []string(nil)},
	{Alpha2: "OR", Alpha3: "ORI", Name: "Oriya", AltNames: []string(nil), Tags: []string{"oriya"}, Users: []string(nil)},
	{Alpha2: "PL", Alpha3: "POL", Name: "Polish", AltNames: []string(nil), Tags: []string{"polish"}, Users: []string{"POL"}},
	{Alpha2: "TG", Alpha3: "TGK", Name: "Tajik", AltNames: []string(nil), Tags: []string{"tajik"}, Users: []string{"TJK"}},
	{Alpha2: "CE", Alpha3: "CHE", Name: "Chechen", AltNames: []string(nil), Tags: []string{"chechen"}, Users: []string(nil)},
	{Alpha2: "HA", Alpha3: "HAU", Name: "Hausa", AltNames: []string(nil), Tags: []string{"hausa"}, Users: []string(nil)},
	{Alpha2: "MG", Alpha3: "MLG", Name: "Malagasy", AltNames: []string(nil), Tags: []string{"malagasy"}, Users: []string{"MDG"}},
	{Alpha2: "NE", Alpha3: "NEP", Name: "Nepali", AltNames: []string(nil), Tags: []string{"nepali"}, Users: []string{"NPL"}},
	{Alpha2: "OM", Alpha3: "ORM", Name: "Oromo", AltNames: []string(nil), Tags: []string{"oromo"}, Users: []string(nil)},
	{Alpha2: "TE", Alpha3: "TEL", Name: "Telugu", AltNames: []string(nil), Tags: []string{"telugu"}, Users: []string(nil)},
}
