package language

// Updated at: 2021-01-21 17:51:25.323166459 +0300 MSK m=+1.201249815
var List = []Language{
	{
		Alpha3:   "EPO",
		Alpha2:   "EO",
		Name:     "Esperanto",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"esperanto"},
	},
	{
		Alpha3:   "TIR",
		Alpha2:   "TI",
		Name:     "Tigrinya",
		Users:    []string{"ERI"},
		AltNames: []string(nil),
		Tags:     []string{"tigrinya"},
	},
	{
		Alpha3:   "GLE",
		Alpha2:   "GA",
		Name:     "Irish",
		Users:    []string{"IRL"},
		AltNames: []string(nil),
		Tags:     []string{"irish"},
	},
	{
		Alpha3:   "NOR",
		Alpha2:   "NO",
		Name:     "Norwegian",
		Users:    []string{"BVT", "NOR", "SJM"},
		AltNames: []string(nil),
		Tags:     []string{"norwegian"},
	},
	{
		Alpha3:   "WLN",
		Alpha2:   "WA",
		Name:     "Walloon",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"walloon"},
	},
	{
		Alpha3:   "FIN",
		Alpha2:   "FI",
		Name:     "Finnish",
		Users:    []string{"FIN"},
		AltNames: []string(nil),
		Tags:     []string{"finnish"},
	},
	{
		Alpha3:   "KAZ",
		Alpha2:   "KK",
		Name:     "Kazakh",
		Users:    []string{"KAZ"},
		AltNames: []string(nil),
		Tags:     []string{"kazakh"},
	},
	{
		Alpha3:   "EWE",
		Alpha2:   "EE",
		Name:     "Ewe",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ewe"},
	},
	{
		Alpha3:   "HIN",
		Alpha2:   "HI",
		Name:     "Hindi",
		Users:    []string{"IND", "FJI"},
		AltNames: []string(nil),
		Tags:     []string{"hindi"},
	},
	{
		Alpha3:   "IND",
		Alpha2:   "ID",
		Name:     "Indonesian",
		Users:    []string{"IDN"},
		AltNames: []string(nil),
		Tags:     []string{"indonesian"},
	},
	{
		Alpha3:   "KAS",
		Alpha2:   "KS",
		Name:     "Kashmiri",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"kashmiri"},
	},
	{
		Alpha3:   "URD",
		Alpha2:   "UR",
		Name:     "Urdu",
		Users:    []string{"PAK", "FJI"},
		AltNames: []string(nil),
		Tags:     []string{"urdu"},
	},
	{
		Alpha3:   "AZE",
		Alpha2:   "AZ",
		Name:     "Azerbaijani",
		Users:    []string{"AZE"},
		AltNames: []string(nil),
		Tags:     []string{"azerbaijani"},
	},
	{
		Alpha3:   "ENG",
		Alpha2:   "EN",
		Name:     "English",
		Users:    []string{"PHL", "SYC", "GRD", "TZA", "ZMB", "SDN", "VIR", "HKG", "TON", "SXM", "ZWE", "COK", "SGS", "TTO", "ATA", "MHL", "GBR", "VCT", "SWZ", "TUV", "BWA", "CCK", "ERI", "VGB", "KNA", "AIA", "MUS", "VUT", "BLZ", "SHN", "ATG", "NRU", "IMN", "FSM", "CXR", "HMD", "NIU", "SLE", "JEY", "JAM", "RWA", "FLK", "KIR", "ZAF", "IND", "AUS", "PCN", "BHS", "GGY", "MAF", "NZL", "PAK", "GMB", "PNG", "WSM", "CUW", "GHA", "IRL", "BRB", "BMU", "MSR", "SGP", "MWI", "MNP", "USA", "KEN", "LSO", "CMR", "CYM", "GUM", "NAM", "NGA", "NFK", "TKL", "PRI", "SSD", "LBR", "MLT", "PLW", "ASM", "TCA", "SLB", "FJI", "UGA", "CAN", "DMA", "IOT", "LCA", "GIB", "GUY"},
		AltNames: []string(nil),
		Tags:     []string{"english"},
	},
	{
		Alpha3:   "KOM",
		Alpha2:   "KV",
		Name:     "Komi",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"komi"},
	},
	{
		Alpha3:   "KON",
		Alpha2:   "KG",
		Name:     "Kongo",
		Users:    []string{"COD"},
		AltNames: []string(nil),
		Tags:     []string{"kongo"},
	},
	{
		Alpha3:   "KUR",
		Alpha2:   "KU",
		Name:     "Kurdish",
		Users:    []string{"IRQ"},
		AltNames: []string(nil),
		Tags:     []string{"kurdish"},
	},
	{
		Alpha3:   "MAH",
		Alpha2:   "MH",
		Name:     "Marshallese",
		Users:    []string{"MHL"},
		AltNames: []string(nil),
		Tags:     []string{"marshallese"},
	},
	{
		Alpha3:   "AMH",
		Alpha2:   "AM",
		Name:     "Amharic",
		Users:    []string{"ETH"},
		AltNames: []string(nil),
		Tags:     []string{"amharic"},
	},
	{
		Alpha3:   "HAU",
		Alpha2:   "HA",
		Name:     "Hausa",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"hausa"},
	},
	{
		Alpha3:   "SOM",
		Alpha2:   "SO",
		Name:     "Somali",
		Users:    []string{"SOM"},
		AltNames: []string(nil),
		Tags:     []string{"somali"},
	},
	{
		Alpha3:   "SWA",
		Alpha2:   "SW",
		Name:     "Swahili",
		Users:    []string{"TZA", "COD", "KEN", "UGA"},
		AltNames: []string(nil),
		Tags:     []string{"swahili"},
	},
	{
		Alpha3:   "TGK",
		Alpha2:   "TG",
		Name:     "Tajik",
		Users:    []string{"TJK"},
		AltNames: []string(nil),
		Tags:     []string{"tajik"},
	},
	{
		Alpha3:   "TUK",
		Alpha2:   "TK",
		Name:     "Turkmen",
		Users:    []string{"AFG", "TKM"},
		AltNames: []string(nil),
		Tags:     []string{"turkmen"},
	},
	{
		Alpha3:   "VEN",
		Alpha2:   "VE",
		Name:     "Venda",
		Users:    []string{"ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"venda"},
	},
	{
		Alpha3:   "IBO",
		Alpha2:   "IG",
		Name:     "Igbo",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"igbo"},
	},
	{
		Alpha3:   "SAN",
		Alpha2:   "SA",
		Name:     "Sanskrit",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"sanskrit"},
	},
	{
		Alpha3:   "SMO",
		Alpha2:   "SM",
		Name:     "Samoan",
		Users:    []string{"WSM", "ASM"},
		AltNames: []string(nil),
		Tags:     []string{"samoan"},
	},
	{
		Alpha3:   "GRN",
		Alpha2:   "GN",
		Name:     "Guarani",
		Users:    []string{"ARG", "PRY"},
		AltNames: []string(nil),
		Tags:     []string{"guarani"},
	},
	{
		Alpha3:   "LAO",
		Alpha2:   "LO",
		Name:     "Lao",
		Users:    []string{"LAO"},
		AltNames: []string(nil),
		Tags:     []string{"lao"},
	},
	{
		Alpha3:   "HEB",
		Alpha2:   "HE",
		Name:     "Hebrew",
		Users:    []string{"ISR"},
		AltNames: []string(nil),
		Tags:     []string{"hebrew"},
	},
	{
		Alpha3:   "PLI",
		Alpha2:   "PI",
		Name:     "Pali",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"pali"},
	},
	{
		Alpha3:   "SLV",
		Alpha2:   "SL",
		Name:     "Slovenian",
		Users:    []string{"SVN"},
		AltNames: []string(nil),
		Tags:     []string{"slovenian"},
	},
	{
		Alpha3:   "FIJ",
		Alpha2:   "FJ",
		Name:     "Fijian",
		Users:    []string{"FJI"},
		AltNames: []string(nil),
		Tags:     []string{"fijian"},
	},
	{
		Alpha3:   "GLV",
		Alpha2:   "GV",
		Name:     "Manx",
		Users:    []string{"IMN"},
		AltNames: []string(nil),
		Tags:     []string{"manx"},
	},
	{
		Alpha3:   "MON",
		Alpha2:   "MN",
		Name:     "Mongolian",
		Users:    []string{"MNG"},
		AltNames: []string(nil),
		Tags:     []string{"mongolian"},
	},
	{
		Alpha3:   "THA",
		Alpha2:   "TH",
		Name:     "Thai",
		Users:    []string{"THA"},
		AltNames: []string(nil),
		Tags:     []string{"thai"},
	},
	{
		Alpha3:   "TSO",
		Alpha2:   "TS",
		Name:     "Tsonga",
		Users:    []string{"ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"tsonga"},
	},
	{
		Alpha3:   "XHO",
		Alpha2:   "XH",
		Name:     "Xhosa",
		Users:    []string{"ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"xhosa"},
	},
	{
		Alpha3:   "IKU",
		Alpha2:   "IU",
		Name:     "Inuktitut",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"inuktitut"},
	},
	{
		Alpha3:   "LIT",
		Alpha2:   "LT",
		Name:     "Lithuanian",
		Users:    []string{"LTU"},
		AltNames: []string(nil),
		Tags:     []string{"lithuanian"},
	},
	{
		Alpha3:   "ORM",
		Alpha2:   "OM",
		Name:     "Oromo",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"oromo"},
	},
	{
		Alpha3:   "SND",
		Alpha2:   "SD",
		Name:     "Sindhi",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"sindhi"},
	},
	{
		Alpha3:   "TAM",
		Alpha2:   "TA",
		Name:     "Tamil",
		Users:    []string{"LKA", "SGP"},
		AltNames: []string(nil),
		Tags:     []string{"tamil"},
	},
	{
		Alpha3:   "DAN",
		Alpha2:   "DA",
		Name:     "Danish",
		Users:    []string{"DNK"},
		AltNames: []string(nil),
		Tags:     []string{"danish"},
	},
	{
		Alpha3:   "GLG",
		Alpha2:   "GL",
		Name:     "Galician",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"galician"},
	},
	{
		Alpha3:   "FAO",
		Alpha2:   "FO",
		Name:     "Faroese",
		Users:    []string{"FRO"},
		AltNames: []string(nil),
		Tags:     []string{"faroese"},
	},
	{
		Alpha3:   "KAU",
		Alpha2:   "KR",
		Name:     "Kanuri",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"kanuri"},
	},
	{
		Alpha3:   "SRD",
		Alpha2:   "SC",
		Name:     "Sardinian",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"sardinian"},
	},
	{
		Alpha3:   "BOS",
		Alpha2:   "BS",
		Name:     "Bosnian",
		Users:    []string{"MNE", "BIH"},
		AltNames: []string(nil),
		Tags:     []string{"bosnian"},
	},
	{
		Alpha3:   "CRE",
		Alpha2:   "CR",
		Name:     "Cree",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"cree"},
	},
	{
		Alpha3:   "HER",
		Alpha2:   "HZ",
		Name:     "Herero",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"herero"},
	},
	{
		Alpha3:   "TWI",
		Alpha2:   "TW",
		Name:     "Twi",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"twi"},
	},
	{
		Alpha3:   "SUN",
		Alpha2:   "SU",
		Name:     "Sundanese",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"sundanese"},
	},
	{
		Alpha3:   "BUL",
		Alpha2:   "BG",
		Name:     "Bulgarian",
		Users:    []string{"BGR"},
		AltNames: []string(nil),
		Tags:     []string{"bulgarian"},
	},
	{
		Alpha3:   "KAN",
		Alpha2:   "KN",
		Name:     "Kannada",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"kannada"},
	},
	{
		Alpha3:   "LIN",
		Alpha2:   "LN",
		Name:     "Lingala",
		Users:    []string{"COD", "COG"},
		AltNames: []string(nil),
		Tags:     []string{"lingala"},
	},
	{
		Alpha3:   "ITA",
		Alpha2:   "IT",
		Name:     "Italian",
		Users:    []string{"ITA", "CHE", "VAT", "SMR"},
		AltNames: []string(nil),
		Tags:     []string{"italian"},
	},
	{
		Alpha3:   "KOR",
		Alpha2:   "KO",
		Name:     "Korean",
		Users:    []string{"KOR", "PRK"},
		AltNames: []string(nil),
		Tags:     []string{"korean"},
	},
	{
		Alpha3:   "OJI",
		Alpha2:   "OJ",
		Name:     "Ojibwa",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ojibwa"},
	},
	{
		Alpha3:   "ROH",
		Alpha2:   "RM",
		Name:     "Romansh",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"romansh"},
	},
	{
		Alpha3:   "UKR",
		Alpha2:   "UK",
		Name:     "Ukrainian",
		Users:    []string{"UKR"},
		AltNames: []string(nil),
		Tags:     []string{"ukrainian"},
	},
	{
		Alpha3:   "CHA",
		Alpha2:   "CH",
		Name:     "Chamorro",
		Users:    []string{"MNP", "GUM"},
		AltNames: []string(nil),
		Tags:     []string{"chamorro"},
	},
	{
		Alpha3:   "FUL",
		Alpha2:   "FF",
		Name:     "Fulah",
		Users:    []string{"BFA", "GIN"},
		AltNames: []string(nil),
		Tags:     []string{"fulah"},
	},
	{
		Alpha3:   "YID",
		Alpha2:   "YI",
		Name:     "Yiddish",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"yiddish"},
	},
	{
		Alpha3:   "AYM",
		Alpha2:   "AY",
		Name:     "Aymara",
		Users:    []string{"BOL"},
		AltNames: []string(nil),
		Tags:     []string{"aymara"},
	},
	{
		Alpha3:   "QUE",
		Alpha2:   "QU",
		Name:     "Quechua",
		Users:    []string{"BOL"},
		AltNames: []string(nil),
		Tags:     []string{"quechua"},
	},
	{
		Alpha3:   "NDO",
		Alpha2:   "NG",
		Name:     "Ndonga",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ndonga"},
	},
	{
		Alpha3:   "NEP",
		Alpha2:   "NE",
		Name:     "Nepali",
		Users:    []string{"NPL"},
		AltNames: []string(nil),
		Tags:     []string{"nepali"},
	},
	{
		Alpha3:   "POL",
		Alpha2:   "PL",
		Name:     "Polish",
		Users:    []string{"POL"},
		AltNames: []string(nil),
		Tags:     []string{"polish"},
	},
	{
		Alpha3:   "BIS",
		Alpha2:   "BI",
		Name:     "Bislama",
		Users:    []string{"VUT"},
		AltNames: []string(nil),
		Tags:     []string{"bislama"},
	},
	{
		Alpha3:   "KIN",
		Alpha2:   "RW",
		Name:     "Kinyarwanda",
		Users:    []string{"RWA"},
		AltNames: []string(nil),
		Tags:     []string{"kinyarwanda"},
	},
	{
		Alpha3:   "BEN",
		Alpha2:   "BN",
		Name:     "Bengali",
		Users:    []string{"BGD"},
		AltNames: []string(nil),
		Tags:     []string{"bengali"},
	},
	{
		Alpha3:   "COR",
		Alpha2:   "KW",
		Name:     "Cornish",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"cornish"},
	},
	{
		Alpha3:   "SNA",
		Alpha2:   "SN",
		Name:     "Shona",
		Users:    []string{"ZWE"},
		AltNames: []string(nil),
		Tags:     []string{"shona"},
	},
	{
		Alpha3:   "AVE",
		Alpha2:   "AE",
		Name:     "Avestan",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"avestan"},
	},
	{
		Alpha3:   "BAK",
		Alpha2:   "BA",
		Name:     "Bashkir",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"bashkir"},
	},
	{
		Alpha3:   "SRP",
		Alpha2:   "SR",
		Name:     "Serbian",
		Users:    []string{"KOS", "MNE", "BIH", "SRB"},
		AltNames: []string(nil),
		Tags:     []string{"serbian"},
	},
	{
		Alpha3:   "TGL",
		Alpha2:   "TL",
		Name:     "Tagalog",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"tagalog"},
	},
	{
		Alpha3:   "VIE",
		Alpha2:   "VI",
		Name:     "Vietnamese",
		Users:    []string{"VNM"},
		AltNames: []string(nil),
		Tags:     []string{"vietnamese"},
	},
	{
		Alpha3:   "ABK",
		Alpha2:   "AB",
		Name:     "Abkhazian",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"abkhazian"},
	},
	{
		Alpha3:   "CHV",
		Alpha2:   "CV",
		Name:     "Chuvash",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"chuvash"},
	},
	{
		Alpha3:   "AKA",
		Alpha2:   "AK",
		Name:     "Akan",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"akan"},
	},
	{
		Alpha3:   "GUJ",
		Alpha2:   "GU",
		Name:     "Gujarati",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"gujarati"},
	},
	{
		Alpha3:   "LAT",
		Alpha2:   "LA",
		Name:     "Latin",
		Users:    []string{"VAT"},
		AltNames: []string(nil),
		Tags:     []string{"latin"},
	},
	{
		Alpha3:   "COS",
		Alpha2:   "CO",
		Name:     "Corsican",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"corsican"},
	},
	{
		Alpha3:   "DZO",
		Alpha2:   "DZ",
		Name:     "Dzongkha",
		Users:    []string{"BTN"},
		AltNames: []string(nil),
		Tags:     []string{"dzongkha"},
	},
	{
		Alpha3:   "IPK",
		Alpha2:   "IK",
		Name:     "Inupiaq",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"inupiaq"},
	},
	{
		Alpha3:   "SWE",
		Alpha2:   "SV",
		Name:     "Swedish",
		Users:    []string{"ALA", "SWE", "FIN"},
		AltNames: []string(nil),
		Tags:     []string{"swedish"},
	},
	{
		Alpha3:   "SSW",
		Alpha2:   "SS",
		Name:     "Swati",
		Users:    []string{"SWZ", "ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"swati"},
	},
	{
		Alpha3:   "ARA",
		Alpha2:   "AR",
		Name:     "Arabic",
		Users:    []string{"YEM", "KWT", "SDN", "OMN", "QAT", "ERI", "ARE", "SAU", "COM", "IRQ", "SYR", "TCD", "LBN", "ISR", "EGY", "LBY", "DZA", "PSE", "MRT", "MAR", "JOR", "TUN", "BHR", "DJI", "SOM"},
		AltNames: []string(nil),
		Tags:     []string{"arabic"},
	},
	{
		Alpha3:   "EST",
		Alpha2:   "ET",
		Name:     "Estonian",
		Users:    []string{"EST"},
		AltNames: []string(nil),
		Tags:     []string{"estonian"},
	},
	{
		Alpha3:   "RUN",
		Alpha2:   "RN",
		Name:     "Rundi",
		Users:    []string{"BDI"},
		AltNames: []string(nil),
		Tags:     []string{"rundi"},
	},
	{
		Alpha3:   "JPN",
		Alpha2:   "JA",
		Name:     "Japanese",
		Users:    []string{"JPN"},
		AltNames: []string(nil),
		Tags:     []string{"japanese"},
	},
	{
		Alpha3:   "MAR",
		Alpha2:   "MR",
		Name:     "Marathi",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"marathi"},
	},
	{
		Alpha3:   "AFR",
		Alpha2:   "AF",
		Name:     "Afrikaans",
		Users:    []string{"ZAF", "NAM"},
		AltNames: []string(nil),
		Tags:     []string{"afrikaans"},
	},
	{
		Alpha3:   "BEL",
		Alpha2:   "BE",
		Name:     "Belarusian",
		Users:    []string{"BLR"},
		AltNames: []string(nil),
		Tags:     []string{"belarusian"},
	},
	{
		Alpha3:   "MLG",
		Alpha2:   "MG",
		Name:     "Malagasy",
		Users:    []string{"MDG"},
		AltNames: []string(nil),
		Tags:     []string{"malagasy"},
	},
	{
		Alpha3:   "SAG",
		Alpha2:   "SG",
		Name:     "Sango",
		Users:    []string{"CAF"},
		AltNames: []string(nil),
		Tags:     []string{"sango"},
	},
	{
		Alpha3:   "TAH",
		Alpha2:   "TY",
		Name:     "Tahitian",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"tahitian"},
	},
	{
		Alpha3:   "TAT",
		Alpha2:   "TT",
		Name:     "Tatar",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"tatar"},
	},
	{
		Alpha3:   "TEL",
		Alpha2:   "TE",
		Name:     "Telugu",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"telugu"},
	},
	{
		Alpha3:   "JAV",
		Alpha2:   "JV",
		Name:     "Javanese",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"javanese"},
	},
	{
		Alpha3:   "MAL",
		Alpha2:   "ML",
		Name:     "Malayalam",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"malayalam"},
	},
	{
		Alpha3:   "HUN",
		Alpha2:   "HU",
		Name:     "Hungarian",
		Users:    []string{"HUN"},
		AltNames: []string(nil),
		Tags:     []string{"hungarian"},
	},
	{
		Alpha3:   "LUG",
		Alpha2:   "LG",
		Name:     "Ganda",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ganda"},
	},
	{
		Alpha3:   "NAU",
		Alpha2:   "NA",
		Name:     "Nauru",
		Users:    []string{"NRU"},
		AltNames: []string(nil),
		Tags:     []string{"nauru"},
	},
	{
		Alpha3:   "ARG",
		Alpha2:   "AN",
		Name:     "Aragonese",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"aragonese"},
	},
	{
		Alpha3:   "HRV",
		Alpha2:   "HR",
		Name:     "Croatian",
		Users:    []string{"HRV", "MNE", "BIH"},
		AltNames: []string(nil),
		Tags:     []string{"croatian"},
	},
	{
		Alpha3:   "MLT",
		Alpha2:   "MT",
		Name:     "Maltese",
		Users:    []string{"MLT"},
		AltNames: []string(nil),
		Tags:     []string{"maltese"},
	},
	{
		Alpha3:   "POR",
		Alpha2:   "PT",
		Name:     "Portuguese",
		Users:    []string{"MOZ", "MAC", "AGO", "BRA", "STP", "CPV", "GNB", "PRT", "TLS"},
		AltNames: []string(nil),
		Tags:     []string{"portuguese"},
	},
	{
		Alpha3:   "TUR",
		Alpha2:   "TR",
		Name:     "Turkish",
		Users:    []string{"CYP", "TUR"},
		AltNames: []string(nil),
		Tags:     []string{"turkish"},
	},
	{
		Alpha3:   "UZB",
		Alpha2:   "UZ",
		Name:     "Uzbek",
		Users:    []string{"UZB", "AFG"},
		AltNames: []string(nil),
		Tags:     []string{"uzbek"},
	},
	{
		Alpha3:   "YOR",
		Alpha2:   "YO",
		Name:     "Yoruba",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"yoruba"},
	},
	{
		Alpha3:   "ZUL",
		Alpha2:   "ZU",
		Name:     "Zulu",
		Users:    []string{"ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"zulu"},
	},
	{
		Alpha3:   "ASM",
		Alpha2:   "AS",
		Name:     "Assamese",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"assamese"},
	},
	{
		Alpha3:   "BRE",
		Alpha2:   "BR",
		Name:     "Breton",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"breton"},
	},
	{
		Alpha3:   "CHE",
		Alpha2:   "CE",
		Name:     "Chechen",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"chechen"},
	},
	{
		Alpha3:   "TSN",
		Alpha2:   "TN",
		Name:     "Tswana",
		Users:    []string{"BWA", "ZAF"},
		AltNames: []string(nil),
		Tags:     []string{"tswana"},
	},
	{
		Alpha3:   "AAR",
		Alpha2:   "AA",
		Name:     "Afar",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"afar"},
	},
	{
		Alpha3:   "BAM",
		Alpha2:   "BM",
		Name:     "Bambara",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"bambara"},
	},
	{
		Alpha3:   "LAV",
		Alpha2:   "LV",
		Name:     "Latvian",
		Users:    []string{"LVA"},
		AltNames: []string(nil),
		Tags:     []string{"latvian"},
	},
	{
		Alpha3:   "ORI",
		Alpha2:   "OR",
		Name:     "Oriya",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"oriya"},
	},
	{
		Alpha3:   "RUS",
		Alpha2:   "RU",
		Name:     "Russian",
		Users:    []string{"ATA", "UZB", "KGZ", "BLR", "TKM", "RUS", "ARM", "TJK", "KAZ"},
		AltNames: []string(nil),
		Tags:     []string{"russian"},
	},
	{
		Alpha3:   "WOL",
		Alpha2:   "WO",
		Name:     "Wolof",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"wolof"},
	},
	{
		Alpha3:   "AVA",
		Alpha2:   "AV",
		Name:     "Avaric",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"avaric"},
	},
	{
		Alpha3:   "IDO",
		Alpha2:   "IO",
		Name:     "Ido",
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ido"},
	},
}
