package language

// Updated at: 2021-01-05 23:22:15.753865541 +0300 MSK m=+0.996623938
var List = []Language{
	{
		Alpha3: "KOM",
		Alpha2: "KV",
		Name:   "Komi",
		Users:  []string(nil),
	},
	{
		Alpha3: "URD",
		Alpha2: "UR",
		Name:   "Urdu",
		Users:  []string{"PAK", "FJI"},
	},
	{
		Alpha3: "XHO",
		Alpha2: "XH",
		Name:   "Xhosa",
		Users:  []string{"ZAF"},
	},
	{
		Alpha3: "EWE",
		Alpha2: "EE",
		Name:   "Ewe",
		Users:  []string(nil),
	},
	{
		Alpha3: "GRN",
		Alpha2: "GN",
		Name:   "Guarani",
		Users:  []string{"PRY", "ARG"},
	},
	{
		Alpha3: "HUN",
		Alpha2: "HU",
		Name:   "Hungarian",
		Users:  []string{"HUN"},
	},
	{
		Alpha3: "TIR",
		Alpha2: "TI",
		Name:   "Tigrinya",
		Users:  []string{"ERI"},
	},
	{
		Alpha3: "KUR",
		Alpha2: "KU",
		Name:   "Kurdish",
		Users:  []string{"IRQ"},
	},
	{
		Alpha3: "YID",
		Alpha2: "YI",
		Name:   "Yiddish",
		Users:  []string(nil),
	},
	{
		Alpha3: "MON",
		Alpha2: "MN",
		Name:   "Mongolian",
		Users:  []string{"MNG"},
	},
	{
		Alpha3: "POL",
		Alpha2: "PL",
		Name:   "Polish",
		Users:  []string{"POL"},
	},
	{
		Alpha3: "RUS",
		Alpha2: "RU",
		Name:   "Russian",
		Users:  []string{"KGZ", "ATA", "ARM", "RUS", "TJK", "UZB", "BLR", "KAZ", "TKM"},
	},
	{
		Alpha3: "AKA",
		Alpha2: "AK",
		Name:   "Akan",
		Users:  []string(nil),
	},
	{
		Alpha3: "EPO",
		Alpha2: "EO",
		Name:   "Esperanto",
		Users:  []string(nil),
	},
	{
		Alpha3: "MAL",
		Alpha2: "ML",
		Name:   "Malayalam",
		Users:  []string(nil),
	},
	{
		Alpha3: "AVE",
		Alpha2: "AE",
		Name:   "Avestan",
		Users:  []string(nil),
	},
	{
		Alpha3: "GLV",
		Alpha2: "GV",
		Name:   "Manx",
		Users:  []string{"IMN"},
	},
	{
		Alpha3: "BEL",
		Alpha2: "BE",
		Name:   "Belarusian",
		Users:  []string{"BLR"},
	},
	{
		Alpha3: "KAZ",
		Alpha2: "KK",
		Name:   "Kazakh",
		Users:  []string{"KAZ"},
	},
	{
		Alpha3: "MLG",
		Alpha2: "MG",
		Name:   "Malagasy",
		Users:  []string{"MDG"},
	},
	{
		Alpha3: "NAU",
		Alpha2: "NA",
		Name:   "Nauru",
		Users:  []string{"NRU"},
	},
	{
		Alpha3: "NEP",
		Alpha2: "NE",
		Name:   "Nepali",
		Users:  []string{"NPL"},
	},
	{
		Alpha3: "CHE",
		Alpha2: "CE",
		Name:   "Chechen",
		Users:  []string(nil),
	},
	{
		Alpha3: "FIJ",
		Alpha2: "FJ",
		Name:   "Fijian",
		Users:  []string{"FJI"},
	},
	{
		Alpha3: "IDO",
		Alpha2: "IO",
		Name:   "Ido",
		Users:  []string(nil),
	},
	{
		Alpha3: "MAH",
		Alpha2: "MH",
		Name:   "Marshallese",
		Users:  []string{"MHL"},
	},
	{
		Alpha3: "AVA",
		Alpha2: "AV",
		Name:   "Avaric",
		Users:  []string(nil),
	},
	{
		Alpha3: "DZO",
		Alpha2: "DZ",
		Name:   "Dzongkha",
		Users:  []string{"BTN"},
	},
	{
		Alpha3: "SAN",
		Alpha2: "SA",
		Name:   "Sanskrit",
		Users:  []string(nil),
	},
	{
		Alpha3: "BAM",
		Alpha2: "BM",
		Name:   "Bambara",
		Users:  []string(nil),
	},
	{
		Alpha3: "COR",
		Alpha2: "KW",
		Name:   "Cornish",
		Users:  []string(nil),
	},
	{
		Alpha3: "GLG",
		Alpha2: "GL",
		Name:   "Galician",
		Users:  []string(nil),
	},
	{
		Alpha3: "IPK",
		Alpha2: "IK",
		Name:   "Inupiaq",
		Users:  []string(nil),
	},
	{
		Alpha3: "THA",
		Alpha2: "TH",
		Name:   "Thai",
		Users:  []string{"THA"},
	},
	{
		Alpha3: "ABK",
		Alpha2: "AB",
		Name:   "Abkhazian",
		Users:  []string(nil),
	},
	{
		Alpha3: "AMH",
		Alpha2: "AM",
		Name:   "Amharic",
		Users:  []string{"ETH"},
	},
	{
		Alpha3: "TAM",
		Alpha2: "TA",
		Name:   "Tamil",
		Users:  []string{"LKA", "SGP"},
	},
	{
		Alpha3: "TGK",
		Alpha2: "TG",
		Name:   "Tajik",
		Users:  []string{"TJK"},
	},
	{
		Alpha3: "BOS",
		Alpha2: "BS",
		Name:   "Bosnian",
		Users:  []string{"BIH", "MNE"},
	},
	{
		Alpha3: "JPN",
		Alpha2: "JA",
		Name:   "Japanese",
		Users:  []string{"JPN"},
	},
	{
		Alpha3: "KIN",
		Alpha2: "RW",
		Name:   "Kinyarwanda",
		Users:  []string{"RWA"},
	},
	{
		Alpha3: "LIN",
		Alpha2: "LN",
		Name:   "Lingala",
		Users:  []string{"COD", "COG"},
	},
	{
		Alpha3: "ORI",
		Alpha2: "OR",
		Name:   "Oriya",
		Users:  []string(nil),
	},
	{
		Alpha3: "VEN",
		Alpha2: "VE",
		Name:   "Venda",
		Users:  []string{"ZAF"},
	},
	{
		Alpha3: "HIN",
		Alpha2: "HI",
		Name:   "Hindi",
		Users:  []string{"IND", "FJI"},
	},
	{
		Alpha3: "SLV",
		Alpha2: "SL",
		Name:   "Slovenian",
		Users:  []string{"SVN"},
	},
	{
		Alpha3: "ORM",
		Alpha2: "OM",
		Name:   "Oromo",
		Users:  []string(nil),
	},
	{
		Alpha3: "PLI",
		Alpha2: "PI",
		Name:   "Pali",
		Users:  []string(nil),
	},
	{
		Alpha3: "SWA",
		Alpha2: "SW",
		Name:   "Swahili",
		Users:  []string{"KEN", "COD", "UGA", "TZA"},
	},
	{
		Alpha3: "WOL",
		Alpha2: "WO",
		Name:   "Wolof",
		Users:  []string(nil),
	},
	{
		Alpha3: "ASM",
		Alpha2: "AS",
		Name:   "Assamese",
		Users:  []string(nil),
	},
	{
		Alpha3: "SOM",
		Alpha2: "SO",
		Name:   "Somali",
		Users:  []string{"SOM"},
	},
	{
		Alpha3: "TSO",
		Alpha2: "TS",
		Name:   "Tsonga",
		Users:  []string{"ZAF"},
	},
	{
		Alpha3: "UKR",
		Alpha2: "UK",
		Name:   "Ukrainian",
		Users:  []string{"UKR"},
	},
	{
		Alpha3: "ENG",
		Alpha2: "EN",
		Name:   "English",
		Users:  []string{"VGB", "CXR", "COK", "KEN", "ATA", "GUY", "ZMB", "FLK", "RWA", "PRI", "HMD", "SLB", "CCK", "ZWE", "SHN", "PLW", "SWZ", "PHL", "WSM", "ERI", "NFK", "PNG", "MNP", "GGY", "MWI", "AIA", "LBR", "GHA", "IMN", "GUM", "NZL", "DMA", "GRD", "VUT", "MLT", "SXM", "BLZ", "SLE", "IOT", "PCN", "GBR", "NIU", "CYM", "TKL", "HKG", "LCA", "SSD", "SDN", "CMR", "FSM", "NAM", "NGA", "SGS", "TTO", "MAF", "TON", "ATG", "BHS", "PAK", "BWA", "CAN", "MUS", "TCA", "AUS", "KIR", "TUV", "IND", "SYC", "FJI", "UGA", "USA", "CUW", "VCT", "MHL", "BRB", "LSO", "GMB", "JEY", "GIB", "ZAF", "ASM", "VIR", "KNA", "JAM", "SGP", "IRL", "BMU", "TZA", "NRU", "MSR"},
	},
	{
		Alpha3: "LAO",
		Alpha2: "LO",
		Name:   "Lao",
		Users:  []string{"LAO"},
	},
	{
		Alpha3: "LUG",
		Alpha2: "LG",
		Name:   "Ganda",
		Users:  []string(nil),
	},
	{
		Alpha3: "ZUL",
		Alpha2: "ZU",
		Name:   "Zulu",
		Users:  []string{"ZAF"},
	},
	{
		Alpha3: "IBO",
		Alpha2: "IG",
		Name:   "Igbo",
		Users:  []string(nil),
	},
	{
		Alpha3: "KAN",
		Alpha2: "KN",
		Name:   "Kannada",
		Users:  []string(nil),
	},
	{
		Alpha3: "MLT",
		Alpha2: "MT",
		Name:   "Maltese",
		Users:  []string{"MLT"},
	},
	{
		Alpha3: "SAG",
		Alpha2: "SG",
		Name:   "Sango",
		Users:  []string{"CAF"},
	},
	{
		Alpha3: "KAS",
		Alpha2: "KS",
		Name:   "Kashmiri",
		Users:  []string(nil),
	},
	{
		Alpha3: "KON",
		Alpha2: "KG",
		Name:   "Kongo",
		Users:  []string{"COD"},
	},
	{
		Alpha3: "NOR",
		Alpha2: "NO",
		Name:   "Norwegian",
		Users:  []string{"NOR", "BVT", "SJM"},
	},
	{
		Alpha3: "CHV",
		Alpha2: "CV",
		Name:   "Chuvash",
		Users:  []string(nil),
	},
	{
		Alpha3: "TAT",
		Alpha2: "TT",
		Name:   "Tatar",
		Users:  []string(nil),
	},
	{
		Alpha3: "TSN",
		Alpha2: "TN",
		Name:   "Tswana",
		Users:  []string{"BWA", "ZAF"},
	},
	{
		Alpha3: "CRE",
		Alpha2: "CR",
		Name:   "Cree",
		Users:  []string(nil),
	},
	{
		Alpha3: "HRV",
		Alpha2: "HR",
		Name:   "Croatian",
		Users:  []string{"HRV", "BIH", "MNE"},
	},
	{
		Alpha3: "SNA",
		Alpha2: "SN",
		Name:   "Shona",
		Users:  []string{"ZWE"},
	},
	{
		Alpha3: "SWE",
		Alpha2: "SV",
		Name:   "Swedish",
		Users:  []string{"SWE", "FIN", "ALA"},
	},
	{
		Alpha3: "ARG",
		Alpha2: "AN",
		Name:   "Aragonese",
		Users:  []string(nil),
	},
	{
		Alpha3: "YOR",
		Alpha2: "YO",
		Name:   "Yoruba",
		Users:  []string(nil),
	},
	{
		Alpha3: "AFR",
		Alpha2: "AF",
		Name:   "Afrikaans",
		Users:  []string{"NAM", "ZAF"},
	},
	{
		Alpha3: "DAN",
		Alpha2: "DA",
		Name:   "Danish",
		Users:  []string{"DNK"},
	},
	{
		Alpha3: "RUN",
		Alpha2: "RN",
		Name:   "Rundi",
		Users:  []string{"BDI"},
	},
	{
		Alpha3: "SSW",
		Alpha2: "SS",
		Name:   "Swati",
		Users:  []string{"SWZ", "ZAF"},
	},
	{
		Alpha3: "TEL",
		Alpha2: "TE",
		Name:   "Telugu",
		Users:  []string(nil),
	},
	{
		Alpha3: "FUL",
		Alpha2: "FF",
		Name:   "Fulah",
		Users:  []string{"GIN", "BFA"},
	},
	{
		Alpha3: "HER",
		Alpha2: "HZ",
		Name:   "Herero",
		Users:  []string(nil),
	},
	{
		Alpha3: "LAT",
		Alpha2: "LA",
		Name:   "Latin",
		Users:  []string{"VAT"},
	},
	{
		Alpha3: "MAR",
		Alpha2: "MR",
		Name:   "Marathi",
		Users:  []string(nil),
	},
	{
		Alpha3: "SMO",
		Alpha2: "SM",
		Name:   "Samoan",
		Users:  []string{"WSM", "ASM"},
	},
	{
		Alpha3: "SRD",
		Alpha2: "SC",
		Name:   "Sardinian",
		Users:  []string(nil),
	},
	{
		Alpha3: "WLN",
		Alpha2: "WA",
		Name:   "Walloon",
		Users:  []string(nil),
	},
	{
		Alpha3: "AZE",
		Alpha2: "AZ",
		Name:   "Azerbaijani",
		Users:  []string{"AZE"},
	},
	{
		Alpha3: "BRE",
		Alpha2: "BR",
		Name:   "Breton",
		Users:  []string(nil),
	},
	{
		Alpha3: "SND",
		Alpha2: "SD",
		Name:   "Sindhi",
		Users:  []string(nil),
	},
	{
		Alpha3: "FAO",
		Alpha2: "FO",
		Name:   "Faroese",
		Users:  []string{"FRO"},
	},
	{
		Alpha3: "HAU",
		Alpha2: "HA",
		Name:   "Hausa",
		Users:  []string(nil),
	},
	{
		Alpha3: "ITA",
		Alpha2: "IT",
		Name:   "Italian",
		Users:  []string{"CHE", "SMR", "ITA", "VAT"},
	},
	{
		Alpha3: "LIT",
		Alpha2: "LT",
		Name:   "Lithuanian",
		Users:  []string{"LTU"},
	},
	{
		Alpha3: "AAR",
		Alpha2: "AA",
		Name:   "Afar",
		Users:  []string(nil),
	},
	{
		Alpha3: "BAK",
		Alpha2: "BA",
		Name:   "Bashkir",
		Users:  []string(nil),
	},
	{
		Alpha3: "BEN",
		Alpha2: "BN",
		Name:   "Bengali",
		Users:  []string{"BGD"},
	},
	{
		Alpha3: "GLE",
		Alpha2: "GA",
		Name:   "Irish",
		Users:  []string{"IRL"},
	},
	{
		Alpha3: "JAV",
		Alpha2: "JV",
		Name:   "Javanese",
		Users:  []string(nil),
	},
	{
		Alpha3: "KAU",
		Alpha2: "KR",
		Name:   "Kanuri",
		Users:  []string(nil),
	},
	{
		Alpha3: "OJI",
		Alpha2: "OJ",
		Name:   "Ojibwa",
		Users:  []string(nil),
	},
	{
		Alpha3: "QUE",
		Alpha2: "QU",
		Name:   "Quechua",
		Users:  []string{"BOL"},
	},
	{
		Alpha3: "SRP",
		Alpha2: "SR",
		Name:   "Serbian",
		Users:  []string{"SRB", "BIH", "KOS", "MNE"},
	},
	{
		Alpha3: "TGL",
		Alpha2: "TL",
		Name:   "Tagalog",
		Users:  []string(nil),
	},
	{
		Alpha3: "TUK",
		Alpha2: "TK",
		Name:   "Turkmen",
		Users:  []string{"AFG", "TKM"},
	},
	{
		Alpha3: "UZB",
		Alpha2: "UZ",
		Name:   "Uzbek",
		Users:  []string{"UZB", "AFG"},
	},
	{
		Alpha3: "CHA",
		Alpha2: "CH",
		Name:   "Chamorro",
		Users:  []string{"MNP", "GUM"},
	},
	{
		Alpha3: "FIN",
		Alpha2: "FI",
		Name:   "Finnish",
		Users:  []string{"FIN"},
	},
	{
		Alpha3: "GUJ",
		Alpha2: "GU",
		Name:   "Gujarati",
		Users:  []string(nil),
	},
	{
		Alpha3: "IKU",
		Alpha2: "IU",
		Name:   "Inuktitut",
		Users:  []string(nil),
	},
	{
		Alpha3: "ROH",
		Alpha2: "RM",
		Name:   "Romansh",
		Users:  []string(nil),
	},
	{
		Alpha3: "TAH",
		Alpha2: "TY",
		Name:   "Tahitian",
		Users:  []string(nil),
	},
	{
		Alpha3: "BUL",
		Alpha2: "BG",
		Name:   "Bulgarian",
		Users:  []string{"BGR"},
	},
	{
		Alpha3: "EST",
		Alpha2: "ET",
		Name:   "Estonian",
		Users:  []string{"EST"},
	},
	{
		Alpha3: "LAV",
		Alpha2: "LV",
		Name:   "Latvian",
		Users:  []string{"LVA"},
	},
	{
		Alpha3: "AYM",
		Alpha2: "AY",
		Name:   "Aymara",
		Users:  []string{"BOL"},
	},
	{
		Alpha3: "BIS",
		Alpha2: "BI",
		Name:   "Bislama",
		Users:  []string{"VUT"},
	},
	{
		Alpha3: "IND",
		Alpha2: "ID",
		Name:   "Indonesian",
		Users:  []string{"IDN"},
	},
	{
		Alpha3: "POR",
		Alpha2: "PT",
		Name:   "Portuguese",
		Users:  []string{"MAC", "TLS", "STP", "CPV", "PRT", "MOZ", "AGO", "BRA", "GNB"},
	},
	{
		Alpha3: "SUN",
		Alpha2: "SU",
		Name:   "Sundanese",
		Users:  []string(nil),
	},
	{
		Alpha3: "VIE",
		Alpha2: "VI",
		Name:   "Vietnamese",
		Users:  []string{"VNM"},
	},
	{
		Alpha3: "ARA",
		Alpha2: "AR",
		Name:   "Arabic",
		Users:  []string{"IRQ", "DJI", "ERI", "MAR", "SOM", "YEM", "QAT", "KWT", "LBN", "OMN", "PSE", "EGY", "ISR", "SDN", "MRT", "LBY", "SYR", "COM", "BHR", "JOR", "TUN", "SAU", "DZA", "ARE", "TCD"},
	},
	{
		Alpha3: "HEB",
		Alpha2: "HE",
		Name:   "Hebrew",
		Users:  []string{"ISR"},
	},
	{
		Alpha3: "KOR",
		Alpha2: "KO",
		Name:   "Korean",
		Users:  []string{"PRK", "KOR"},
	},
	{
		Alpha3: "TWI",
		Alpha2: "TW",
		Name:   "Twi",
		Users:  []string(nil),
	},
	{
		Alpha3: "COS",
		Alpha2: "CO",
		Name:   "Corsican",
		Users:  []string(nil),
	},
	{
		Alpha3: "NDO",
		Alpha2: "NG",
		Name:   "Ndonga",
		Users:  []string(nil),
	},
	{
		Alpha3: "TUR",
		Alpha2: "TR",
		Name:   "Turkish",
		Users:  []string{"TUR", "CYP"},
	},
}
